### ISSUE TITLE
how can i use this code with my case

### ISSUE THREAD

**Issue by tushar4monto** [pandasanjay/php-script-background-processer#2]
Hello 
i want to use this script i have a new order's address latitude and longitude. I  want to get all provider lat and log to this order lat, log distance with use of google API and stored it in database.

Currently this functionality working fine but Customer need to wait for api result so i want to call my function in background

my function is getMoverByLocation($customer_lat,$customer_log,$provider_lat,$provider_log);

i wat to call this function who can i call this ? Please help me.

**Comment by pandasanjay** [comment]
Hi tushar

Sorry for the late reply.

As per your requirement, you want to call this **"getMoverByLocation($customer_lat,$customer_log,$provider_lat,$provider_log);"**  function in background. 

Create a GET service and place the whole functionality in it and pass the Service URL to 
$process=new BackgroundProcess("curl -s -o <Base Path>/log/log_storewav.log **[Your GET service URL to execute]**"); 

It's a simple curl operation happen in background.

Thank you for using my code.
Let me know if you need any clarity.

**Comment by tushar4monto** [comment]
Thanks For Your Replay
