### ISSUE TITLE
Execute function of a file

### ISSUE THREAD

**Issue by cristianDroguett** [pandasanjay/php-script-background-processer#3]
It is not possible to execute a function inside a file, if possible, what should be the command line?

**Comment by pandasanjay** [comment]
Yes, It is possible to execute a function inside a file.
Here is the example:
File name: **index.php**
```
<?php
function func1(){
    echo "Func1 executing.....";
}
foreach ($argv AS $arg){
    function_exists($arg) AND call_user_func($arg);
}
```
From terminal:
`php index.php func1`
**func1** name of the function.

Output:
`Func1 executing.....`

Hope this will help you to solve your problem.
