### ISSUE TITLE
How to write the output of background process?

### ISSUE THREAD

**Issue by ziyaindia** [pandasanjay/php-script-background-processer#4]
I have successfully used your script but not getting output.
How I can write the output of background process?

**Comment by pandasanjay** [comment]
Hi @ziyaindia, 

Thanks for raising this question!

There are two ways you can access your data.

1. **Storing your data in database:** Basically if you want to update something on you DB like payment done or any other operation which you need it in DB. You can achieve this by `connecting to DB` in `process.php` file to update the DB.


2. **Storing data in files:** You can store it in file and read the file to get the data as string.
This is currently not supported in the lib, if you are running a `php script`. If you are using curl then using `-o out.log` file.

I am trying to add the file support to the lib it I will inform once added. For your review.

If you have any other solutions please share as well.

Thanks
Sanjay

**Comment by ziyaindia** [comment]
Dear Sanjay,

Thanks for your reply as I checked with your script its not running as background for me.

I am using codeigniter and trying to run by following code

I have created a library class for backgroundprocess class and load it same place.

See my code ways below:

First Way I tried

```
$this->load->library('backgroundprocess');
$this->backgroundprocess->setCmd("curl -s -o ".$_SERVER['DOCUMENT_ROOT']."/page_control/log/log_background_process.log ".base_url('campaign/do'));
$this->backgroundprocess->start();
```

`$cmd_process = FCPATH."index.php campaign dosend"; // $cmd_process = /var/www/html/page_control/index.php campaign dosend `

Second Way I tried

```
$this->backgroundprocess->setCmd('exec /usr/bin/php '.$cmd_process);
$this->backgroundprocess->start();
```
Third Way I tried

```
$this->backgroundprocess->setCmd('exec php '.$cmd_process);
$this->backgroundprocess->start();
```
Fourth Way I tried

```
$this->backgroundprocess->setCmd('exec /usr/bin/php index.php campaign dosend');
$this->backgroundprocess->start();
```
Fifth Way I tried

```
$this->backgroundprocess->setCmd('exec php index.php campaign dosend');
$this->backgroundprocess->start();
```

I have used following link to call in codeigniter
https://codeigniter.com/userguide3/general/cli.html

Please help me to run this.

Thanks in Advance,
Ziya

**Comment by pandasanjay** [comment]
Hi @ziyaindia 

Sorry for the late replay!

I tried to replicate the same in codeigniter4 and the code is working fine.

Please find the document on how to implement it. 
https://github.com/pandasanjay/php-script-background-processer/tree/feature-1.1#how-to-use-this-inside-codeigniter4

Also added an example for codeigniter4 inside the rape which will help you to try it out.

Please check below link, how to debug and check logs

https://github.com/pandasanjay/php-script-background-processer/tree/feature-1.1#how-to-generate-stdout-and-stderr-in-a-file-recommended-only-for-debugging

Please let me know if you still facing the issue. Then I will try to run with Codeigniter3 and debug it.

Thanks
Sanjay

**Comment by ziyaindia** [comment]
Hi Sanjay,

Thanks for your reply
I am using codeigniter3 and I did same steps that you described even I am also getting processId, but I am calling a function that is writing a log, when I am executing that function directly from browser its writing log successfully, same function when I am calling using background process its not writing log not even making database entries if i added the code for that.

My skype id is - ziyaindia

Please come there i will show you.

Thanks,
Ziya

**Comment by pandasanjay** [comment]
Hi @ziyaindia 

Sorry, again I am not able to help you on skype. 

But I can share the details here, which will help you to solve the problem.

I tried to run using Codeigniter3 and found that there is no issue with `BackgroundProcess.php`

But there is couple of other problems using xampp. 

Here is my finding and how I reproduce and solve them.

Step 1: Follow this step on the below link make sure you take the latest `BackgroundProcess.php` file from `feature-1.1`, Which has some error logging mechanism. 
https://github.com/pandasanjay/php-script-background-processer/tree/feature-1.1#how-to-use-in-codeigniter-3
Step 2: After running the code please you will get an output like this 
```text
//Output
Log path:
stdout: /tmp/out_10
stderr: /tmp/error_out_10
457
```
Step 3: run `cat /tmp/error_out_10`

And let me know what is the error you see. I am sure that will help you to find the solution. 

Some problems, I faced while setting up, if you get the same then the below link will help you to solve.
https://github.com/pandasanjay/php-script-background-processer/tree/feature-1.1#issues-i-faced-while-using-it-with-codeigniter3

Also added a folder `codeigniter3` in examples you can also follow that.

Thanks for not giving up. Good luck!

Thanks
Sanjay

**Comment by pandasanjay** [comment]
Hi @ziyaindia 


Please let me know does the solution worked for you?

Please feel free to raise a PR, if you have solution to the problem.

Thanks
Sanjay

**Comment by ziyaindia** [comment]
Sorry to late reply
I stuck in another issue.
I will let you know once i tested.
