### ISSUE TITLE
Error on CI 3

### ISSUE THREAD

**Issue by fredito1212** [pandasanjay/php-script-background-processer#7]
Hi! i hope i can get some help:

I tried to use it on CI3 as the example but got an error undefenied var $process on line 96 of BackgroundProcess.php, also tried the examples in the project but still giving an undefined offset: 0 on the same line, i´m missing something?!

Thanks for developing this library!

**Comment by pandasanjay** [comment]
Hi @fredito1212 

Please follow this document to run the example

https://www.github.com/pandasanjay/php-script-background-processer/tree/master/examples%2FREADME.md

Please let me know how you are running the application.

Thanks
Sanjay
